# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.delete_list_contacts_bulk_input_object import DeleteListContactsBulkInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestDeleteListContactsBulkInputObject(unittest.TestCase):
    """DeleteListContactsBulkInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteListContactsBulkInputObject(self):
        """Test DeleteListContactsBulkInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.delete_list_contacts_bulk_input_object.DeleteListContactsBulkInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
