# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_list_contacts_ids_response import GetListContactsIdsResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetListContactsIdsResponse(unittest.TestCase):
    """GetListContactsIdsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetListContactsIdsResponse(self):
        """Test GetListContactsIdsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_list_contacts_ids_response.GetListContactsIdsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
