# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.currency import Currency  # noqa: E501
from TextMagic.rest import ApiException


class TestCurrency(unittest.TestCase):
    """Currency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrency(self):
        """Test Currency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.currency.Currency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
