# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.unblock_contacts_bulk_input_object import UnblockContactsBulkInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestUnblockContactsBulkInputObject(unittest.TestCase):
    """UnblockContactsBulkInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnblockContactsBulkInputObject(self):
        """Test UnblockContactsBulkInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.unblock_contacts_bulk_input_object.UnblockContactsBulkInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
