# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.resource_link_response import ResourceLinkResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestResourceLinkResponse(unittest.TestCase):
    """ResourceLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceLinkResponse(self):
        """Test ResourceLinkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.resource_link_response.ResourceLinkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
