# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.message_price_item import MessagePriceItem  # noqa: E501
from TextMagic.rest import ApiException


class TestMessagePriceItem(unittest.TestCase):
    """MessagePriceItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessagePriceItem(self):
        """Test MessagePriceItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.message_price_item.MessagePriceItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
