# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.apiv2emailcampaignsschedule_schedule_params import Apiv2emailcampaignsscheduleScheduleParams  # noqa: E501
from TextMagic.rest import ApiException


class TestApiv2emailcampaignsscheduleScheduleParams(unittest.TestCase):
    """Apiv2emailcampaignsscheduleScheduleParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv2emailcampaignsscheduleScheduleParams(self):
        """Test Apiv2emailcampaignsscheduleScheduleParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.apiv2emailcampaignsschedule_schedule_params.Apiv2emailcampaignsscheduleScheduleParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
