# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.message_in import MessageIn  # noqa: E501
from TextMagic.rest import ApiException


class TestMessageIn(unittest.TestCase):
    """MessageIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageIn(self):
        """Test MessageIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.message_in.MessageIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
