# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_inbound_messages_notification_settings_response import GetInboundMessagesNotificationSettingsResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetInboundMessagesNotificationSettingsResponse(unittest.TestCase):
    """GetInboundMessagesNotificationSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInboundMessagesNotificationSettingsResponse(self):
        """Test GetInboundMessagesNotificationSettingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_inbound_messages_notification_settings_response.GetInboundMessagesNotificationSettingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
