# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_timezones_response import GetTimezonesResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetTimezonesResponse(unittest.TestCase):
    """GetTimezonesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTimezonesResponse(self):
        """Test GetTimezonesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_timezones_response.GetTimezonesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
