# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.send_message_response import SendMessageResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestSendMessageResponse(unittest.TestCase):
    """SendMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageResponse(self):
        """Test SendMessageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.send_message_response.SendMessageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
