# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.clear_and_assign_contacts_to_list_input_object import ClearAndAssignContactsToListInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestClearAndAssignContactsToListInputObject(unittest.TestCase):
    """ClearAndAssignContactsToListInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClearAndAssignContactsToListInputObject(self):
        """Test ClearAndAssignContactsToListInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.clear_and_assign_contacts_to_list_input_object.ClearAndAssignContactsToListInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
