# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.create_contact_input_object import CreateContactInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestCreateContactInputObject(unittest.TestCase):
    """CreateContactInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateContactInputObject(self):
        """Test CreateContactInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.create_contact_input_object.CreateContactInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
