# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.search_lists_paginated_response import SearchListsPaginatedResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestSearchListsPaginatedResponse(unittest.TestCase):
    """SearchListsPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchListsPaginatedResponse(self):
        """Test SearchListsPaginatedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.search_lists_paginated_response.SearchListsPaginatedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
