# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.message_out_sender_source import MessageOutSenderSource  # noqa: E501
from TextMagic.rest import ApiException


class TestMessageOutSenderSource(unittest.TestCase):
    """MessageOutSenderSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageOutSenderSource(self):
        """Test MessageOutSenderSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.message_out_sender_source.MessageOutSenderSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
