# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_messaging_stat_response import GetMessagingStatResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetMessagingStatResponse(unittest.TestCase):
    """GetMessagingStatResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMessagingStatResponse(self):
        """Test GetMessagingStatResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_messaging_stat_response.GetMessagingStatResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
