# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_calls_prices_response import GetCallsPricesResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetCallsPricesResponse(unittest.TestCase):
    """GetCallsPricesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCallsPricesResponse(self):
        """Test GetCallsPricesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_calls_prices_response.GetCallsPricesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
