# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_outbound_messages_history_paginated_response import GetOutboundMessagesHistoryPaginatedResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetOutboundMessagesHistoryPaginatedResponse(unittest.TestCase):
    """GetOutboundMessagesHistoryPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOutboundMessagesHistoryPaginatedResponse(self):
        """Test GetOutboundMessagesHistoryPaginatedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_outbound_messages_history_paginated_response.GetOutboundMessagesHistoryPaginatedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
