# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.unblock_contact_input_object import UnblockContactInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestUnblockContactInputObject(unittest.TestCase):
    """UnblockContactInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnblockContactInputObject(self):
        """Test UnblockContactInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.unblock_contact_input_object.UnblockContactInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
