# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.buy_dedicated_number_input_object import BuyDedicatedNumberInputObject  # noqa: E501
from TextMagic.rest import ApiException


class TestBuyDedicatedNumberInputObject(unittest.TestCase):
    """BuyDedicatedNumberInputObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuyDedicatedNumberInputObject(self):
        """Test BuyDedicatedNumberInputObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.buy_dedicated_number_input_object.BuyDedicatedNumberInputObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
