# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BadRequestResponseErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'common': 'list[str]',
        'fields': 'object'
    }

    attribute_map = {
        'common': 'common',
        'fields': 'fields'
    }

    def __init__(self, common=None, fields=None):  # noqa: E501
        """BadRequestResponseErrors - a model defined in Swagger"""  # noqa: E501

        self._common = None
        self._fields = None
        self.discriminator = None

        if common is not None:
            self.common = common
        if fields is not None:
            self.fields = fields

    @property
    def common(self):
        """Gets the common of this BadRequestResponseErrors.  # noqa: E501

        Array of messages with errors related to the entire request. For example, you did not specify either the **text** or the **templateId** when [sending the message](https://docs.textmagic.com/#tag/Outbound-Messages).   # noqa: E501

        :return: The common of this BadRequestResponseErrors.  # noqa: E501
        :rtype: list[str]
        """
        return self._common

    @common.setter
    def common(self, common):
        """Sets the common of this BadRequestResponseErrors.

        Array of messages with errors related to the entire request. For example, you did not specify either the **text** or the **templateId** when [sending the message](https://docs.textmagic.com/#tag/Outbound-Messages).   # noqa: E501

        :param common: The common of this BadRequestResponseErrors.  # noqa: E501
        :type: list[str]
        """

        self._common = common

    @property
    def fields(self):
        """Gets the fields of this BadRequestResponseErrors.  # noqa: E501

        Associative array. The keys are the POST/PUT parameter names and the values are arrays with error messages for these parameters.   # noqa: E501

        :return: The fields of this BadRequestResponseErrors.  # noqa: E501
        :rtype: object
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this BadRequestResponseErrors.

        Associative array. The keys are the POST/PUT parameter names and the values are arrays with error messages for these parameters.   # noqa: E501

        :param fields: The fields of this BadRequestResponseErrors.  # noqa: E501
        :type: object
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BadRequestResponseErrors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BadRequestResponseErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
