# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from TextMagic.models.contact import Contact
from TextMagic.models.country import Country
from TextMagic.models.tag import Tag
from typing import Optional, Set
from typing_extensions import Self

class Chat(BaseModel):
    """
    Chat
    """ # noqa: E501
    id: StrictInt = Field(description="Chat ID.")
    original_id: Optional[StrictInt] = Field(alias="originalId")
    phone: StrictStr = Field(description="Chat partner's phone number.")
    contact: Optional[Contact]
    unsubscribed_contact_id: Optional[StrictInt] = Field(description="If this field has a value, it means that the chat phone number has been unsubscribed from you and this value is an ID of an Unsubscribed contact entity. See [Get all unsubscribed contacts](https://docs.textmagic.com/#operation/getUnsubscribers).", alias="unsubscribedContactId")
    unread: StrictInt = Field(description="Total unread incoming messages.")
    updated_at: datetime = Field(description="Time when the last incoming message arrived at this chat.", alias="updatedAt")
    status: StrictStr = Field(description="Chat status:   * **a** - Active;   * **c** - Closed;   * **d** - Deleted. ")
    mute: StrictInt = Field(description="Indicates when the chat is muted.")
    last_message: Optional[StrictStr] = Field(description="The last message content of a chat.", alias="lastMessage")
    direction: Optional[StrictStr] = Field(description="Last message type: * **ci** - incoming call; * **co** - outgoing call; * **i** - incoming message; * **o** - outgoing message. ")
    reply_options_type: Optional[StrictStr] = Field(description="Used for chats prices.", alias="replyOptionsType")
    var_from: Optional[StrictStr] = Field(description="If filled, the value will be used as a sender number for all outgoing messages of a chat.", alias="from")
    muted_until: Optional[datetime] = Field(description="Date and time until the chat will be muted.", alias="mutedUntil")
    time_left_mute: StrictInt = Field(description="Time left untill the chat will be unmuted (seconds).", alias="timeLeftMute")
    country: Optional[Country]
    pinned: Optional[StrictBool] = Field(description="Indicates when the chat is pinned.")
    type: StrictStr = Field(description="Chat type.")
    sms_price: Union[StrictFloat, StrictInt] = Field(alias="smsPrice")
    mms_price: Union[StrictFloat, StrictInt] = Field(alias="mmsPrice")
    tags: Optional[List[Tag]] = None
    __properties: ClassVar[List[str]] = ["id", "originalId", "phone", "contact", "unsubscribedContactId", "unread", "updatedAt", "status", "mute", "lastMessage", "direction", "replyOptionsType", "from", "mutedUntil", "timeLeftMute", "country", "pinned", "type", "smsPrice", "mmsPrice", "tags"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['a', 'c', 'd']):
            raise ValueError("must be one of enum values ('a', 'c', 'd')")
        return value

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ci', 'co', 'i', 'o']):
            raise ValueError("must be one of enum values ('ci', 'co', 'i', 'o')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Chat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of contact
        if self.contact:
            _dict['contact'] = self.contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict['country'] = self.country.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # set to None if original_id (nullable) is None
        # and model_fields_set contains the field
        if self.original_id is None and "original_id" in self.model_fields_set:
            _dict['originalId'] = None

        # set to None if contact (nullable) is None
        # and model_fields_set contains the field
        if self.contact is None and "contact" in self.model_fields_set:
            _dict['contact'] = None

        # set to None if unsubscribed_contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.unsubscribed_contact_id is None and "unsubscribed_contact_id" in self.model_fields_set:
            _dict['unsubscribedContactId'] = None

        # set to None if last_message (nullable) is None
        # and model_fields_set contains the field
        if self.last_message is None and "last_message" in self.model_fields_set:
            _dict['lastMessage'] = None

        # set to None if direction (nullable) is None
        # and model_fields_set contains the field
        if self.direction is None and "direction" in self.model_fields_set:
            _dict['direction'] = None

        # set to None if reply_options_type (nullable) is None
        # and model_fields_set contains the field
        if self.reply_options_type is None and "reply_options_type" in self.model_fields_set:
            _dict['replyOptionsType'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if muted_until (nullable) is None
        # and model_fields_set contains the field
        if self.muted_until is None and "muted_until" in self.model_fields_set:
            _dict['mutedUntil'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if pinned (nullable) is None
        # and model_fields_set contains the field
        if self.pinned is None and "pinned" in self.model_fields_set:
            _dict['pinned'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Chat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "originalId": obj.get("originalId"),
            "phone": obj.get("phone"),
            "contact": Contact.from_dict(obj["contact"]) if obj.get("contact") is not None else None,
            "unsubscribedContactId": obj.get("unsubscribedContactId"),
            "unread": obj.get("unread"),
            "updatedAt": obj.get("updatedAt"),
            "status": obj.get("status"),
            "mute": obj.get("mute"),
            "lastMessage": obj.get("lastMessage"),
            "direction": obj.get("direction"),
            "replyOptionsType": obj.get("replyOptionsType"),
            "from": obj.get("from"),
            "mutedUntil": obj.get("mutedUntil"),
            "timeLeftMute": obj.get("timeLeftMute"),
            "country": Country.from_dict(obj["country"]) if obj.get("country") is not None else None,
            "pinned": obj.get("pinned"),
            "type": obj.get("type"),
            "smsPrice": obj.get("smsPrice"),
            "mmsPrice": obj.get("mmsPrice"),
            "tags": [Tag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


