# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Conversation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'direction': 'str',
        'sender': 'str',
        'message_time': 'datetime',
        'text': 'str',
        'receiver': 'str',
        'status': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'session_id': 'int',
        'initiator_id': 'int',
        'message_file_id': 'int',
        'type': 'str',
        'chat_type': 'str',
        'chat_id': 'int',
        'is_edited': 'bool',
        'error_code': 'str',
        'files': 'list[File]',
        'payload': 'MessagePayload',
        'avatar': 'str'
    }

    attribute_map = {
        'id': 'id',
        'direction': 'direction',
        'sender': 'sender',
        'message_time': 'messageTime',
        'text': 'text',
        'receiver': 'receiver',
        'status': 'status',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'session_id': 'sessionId',
        'initiator_id': 'initiatorId',
        'message_file_id': 'messageFileId',
        'type': 'type',
        'chat_type': 'chatType',
        'chat_id': 'chatId',
        'is_edited': 'isEdited',
        'error_code': 'errorCode',
        'files': 'files',
        'payload': 'payload',
        'avatar': 'avatar'
    }

    def __init__(self, id=None, direction=None, sender=None, message_time=None, text=None, receiver=None, status=None, first_name=None, last_name=None, session_id=None, initiator_id=None, message_file_id=None, type=None, chat_type=None, chat_id=None, is_edited=None, error_code=None, files=None, payload=None, avatar=None):  # noqa: E501
        """Conversation - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._direction = None
        self._sender = None
        self._message_time = None
        self._text = None
        self._receiver = None
        self._status = None
        self._first_name = None
        self._last_name = None
        self._session_id = None
        self._initiator_id = None
        self._message_file_id = None
        self._type = None
        self._chat_type = None
        self._chat_id = None
        self._is_edited = None
        self._error_code = None
        self._files = None
        self._payload = None
        self._avatar = None
        self.discriminator = None

        self.id = id
        self.direction = direction
        self.sender = sender
        self.message_time = message_time
        self.text = text
        self.receiver = receiver
        self.status = status
        self.first_name = first_name
        self.last_name = last_name
        self.session_id = session_id
        if initiator_id is not None:
            self.initiator_id = initiator_id
        if message_file_id is not None:
            self.message_file_id = message_file_id
        if type is not None:
            self.type = type
        if chat_type is not None:
            self.chat_type = chat_type
        if chat_id is not None:
            self.chat_id = chat_id
        if is_edited is not None:
            self.is_edited = is_edited
        if error_code is not None:
            self.error_code = error_code
        if files is not None:
            self.files = files
        if payload is not None:
            self.payload = payload
        if avatar is not None:
            self.avatar = avatar

    @property
    def id(self):
        """Gets the id of this Conversation.  # noqa: E501


        :return: The id of this Conversation.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Conversation.


        :param id: The id of this Conversation.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def direction(self):
        """Gets the direction of this Conversation.  # noqa: E501

        Message type: inbound or outbound.   # noqa: E501

        :return: The direction of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this Conversation.

        Message type: inbound or outbound.   # noqa: E501

        :param direction: The direction of this Conversation.  # noqa: E501
        :type: str
        """
        allowed_values = ["in", "out", "o", "i"]  # noqa: E501
        if direction not in allowed_values:
            raise ValueError(
                "Invalid value for `direction` ({0}), must be one of {1}"  # noqa: E501
                .format(direction, allowed_values)
            )

        self._direction = direction

    @property
    def sender(self):
        """Gets the sender of this Conversation.  # noqa: E501

        Sender phone number.  # noqa: E501

        :return: The sender of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this Conversation.

        Sender phone number.  # noqa: E501

        :param sender: The sender of this Conversation.  # noqa: E501
        :type: str
        """

        self._sender = sender

    @property
    def message_time(self):
        """Gets the message_time of this Conversation.  # noqa: E501

        Time when  the message arrived at Textmagic.  # noqa: E501

        :return: The message_time of this Conversation.  # noqa: E501
        :rtype: datetime
        """
        return self._message_time

    @message_time.setter
    def message_time(self, message_time):
        """Sets the message_time of this Conversation.

        Time when  the message arrived at Textmagic.  # noqa: E501

        :param message_time: The message_time of this Conversation.  # noqa: E501
        :type: datetime
        """

        self._message_time = message_time

    @property
    def text(self):
        """Gets the text of this Conversation.  # noqa: E501

        Message text.  # noqa: E501

        :return: The text of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Conversation.

        Message text.  # noqa: E501

        :param text: The text of this Conversation.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def receiver(self):
        """Gets the receiver of this Conversation.  # noqa: E501

        Receiver's phone number.  # noqa: E501

        :return: The receiver of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._receiver

    @receiver.setter
    def receiver(self, receiver):
        """Sets the receiver of this Conversation.

        Receiver's phone number.  # noqa: E501

        :param receiver: The receiver of this Conversation.  # noqa: E501
        :type: str
        """

        self._receiver = receiver

    @property
    def status(self):
        """Gets the status of this Conversation.  # noqa: E501

        Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.  # noqa: E501

        :return: The status of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Conversation.

        Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.  # noqa: E501

        :param status: The status of this Conversation.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def first_name(self):
        """Gets the first_name of this Conversation.  # noqa: E501

        Contact first name.  # noqa: E501

        :return: The first_name of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Conversation.

        Contact first name.  # noqa: E501

        :param first_name: The first_name of this Conversation.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Conversation.  # noqa: E501

        Contact last name.  # noqa: E501

        :return: The last_name of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Conversation.

        Contact last name.  # noqa: E501

        :param last_name: The last_name of this Conversation.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def session_id(self):
        """Gets the session_id of this Conversation.  # noqa: E501

        Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.  # noqa: E501

        :return: The session_id of this Conversation.  # noqa: E501
        :rtype: int
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this Conversation.

        Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.  # noqa: E501

        :param session_id: The session_id of this Conversation.  # noqa: E501
        :type: int
        """

        self._session_id = session_id

    @property
    def initiator_id(self):
        """Gets the initiator_id of this Conversation.  # noqa: E501

        Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.  # noqa: E501

        :return: The initiator_id of this Conversation.  # noqa: E501
        :rtype: int
        """
        return self._initiator_id

    @initiator_id.setter
    def initiator_id(self, initiator_id):
        """Sets the initiator_id of this Conversation.

        Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.  # noqa: E501

        :param initiator_id: The initiator_id of this Conversation.  # noqa: E501
        :type: int
        """

        self._initiator_id = initiator_id

    @property
    def message_file_id(self):
        """Gets the message_file_id of this Conversation.  # noqa: E501

        Message file id.  # noqa: E501

        :return: The message_file_id of this Conversation.  # noqa: E501
        :rtype: int
        """
        return self._message_file_id

    @message_file_id.setter
    def message_file_id(self, message_file_id):
        """Sets the message_file_id of this Conversation.

        Message file id.  # noqa: E501

        :param message_file_id: The message_file_id of this Conversation.  # noqa: E501
        :type: int
        """

        self._message_file_id = message_file_id

    @property
    def type(self):
        """Gets the type of this Conversation.  # noqa: E501

        Message type.  # noqa: E501

        :return: The type of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Conversation.

        Message type.  # noqa: E501

        :param type: The type of this Conversation.  # noqa: E501
        :type: str
        """
        allowed_values = ["text", "image", "audio", "voice", "document", "video", "log", "initial", "note"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def chat_type(self):
        """Gets the chat_type of this Conversation.  # noqa: E501

        Chat type.  # noqa: E501

        :return: The chat_type of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._chat_type

    @chat_type.setter
    def chat_type(self, chat_type):
        """Sets the chat_type of this Conversation.

        Chat type.  # noqa: E501

        :param chat_type: The chat_type of this Conversation.  # noqa: E501
        :type: str
        """
        allowed_values = ["sms", "facebook_messenger", "instagram", "whatsapp_business", "live_chat"]  # noqa: E501
        if chat_type not in allowed_values:
            raise ValueError(
                "Invalid value for `chat_type` ({0}), must be one of {1}"  # noqa: E501
                .format(chat_type, allowed_values)
            )

        self._chat_type = chat_type

    @property
    def chat_id(self):
        """Gets the chat_id of this Conversation.  # noqa: E501

        Chat id.  # noqa: E501

        :return: The chat_id of this Conversation.  # noqa: E501
        :rtype: int
        """
        return self._chat_id

    @chat_id.setter
    def chat_id(self, chat_id):
        """Sets the chat_id of this Conversation.

        Chat id.  # noqa: E501

        :param chat_id: The chat_id of this Conversation.  # noqa: E501
        :type: int
        """

        self._chat_id = chat_id

    @property
    def is_edited(self):
        """Gets the is_edited of this Conversation.  # noqa: E501


        :return: The is_edited of this Conversation.  # noqa: E501
        :rtype: bool
        """
        return self._is_edited

    @is_edited.setter
    def is_edited(self, is_edited):
        """Sets the is_edited of this Conversation.


        :param is_edited: The is_edited of this Conversation.  # noqa: E501
        :type: bool
        """

        self._is_edited = is_edited

    @property
    def error_code(self):
        """Gets the error_code of this Conversation.  # noqa: E501

        Error code.  # noqa: E501

        :return: The error_code of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this Conversation.

        Error code.  # noqa: E501

        :param error_code: The error_code of this Conversation.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    @property
    def files(self):
        """Gets the files of this Conversation.  # noqa: E501


        :return: The files of this Conversation.  # noqa: E501
        :rtype: list[File]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this Conversation.


        :param files: The files of this Conversation.  # noqa: E501
        :type: list[File]
        """

        self._files = files

    @property
    def payload(self):
        """Gets the payload of this Conversation.  # noqa: E501


        :return: The payload of this Conversation.  # noqa: E501
        :rtype: MessagePayload
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this Conversation.


        :param payload: The payload of this Conversation.  # noqa: E501
        :type: MessagePayload
        """

        self._payload = payload

    @property
    def avatar(self):
        """Gets the avatar of this Conversation.  # noqa: E501


        :return: The avatar of this Conversation.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this Conversation.


        :param avatar: The avatar of this Conversation.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Conversation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Conversation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
