# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self

class DoEmailLookupResponse(BaseModel):
    """
    DoEmailLookupResponse
    """ # noqa: E501
    address: StrictStr = Field(description="The email address passed to the call.")
    status: StrictStr = Field(description="The email is `valid` or `invalid`.")
    deliverability: StrictStr = Field(description="The delivery status of the email address is`deliverable`, `undeliverable`. or `unknown`.")
    reason: Optional[StrictStr] = Field(description="The reason why the checked email is invalid/undeliverable.")
    risk: StrictStr = Field(description="The risk score of the email is`high`, `medium`, `low` or `null`.")
    address_type: StrictStr = Field(description="The email address type (domain) is `free` or `corporate`.", alias="addressType")
    is_disposable_address: StrictBool = Field(description="This is `true` if the domain is in the list of disposable email addresses; otherwise, it returns as `false`.", alias="isDisposableAddress")
    suggestion: Optional[StrictStr] = Field(description="Null if nothing is suggested; however, if there is a potential typo in the email address, the closest suggestion is provided.")
    email_role: Optional[StrictStr] = Field(description="Checks the mailbox part of the email to see whether it matches a specific role type (‘admin’, ‘sales’, ‘webmaster’).", alias="emailRole")
    local_part: StrictStr = Field(description="The local part of the email address.", alias="localPart")
    domain_part: StrictStr = Field(description="The domain part of the email address.", alias="domainPart")
    exchange: Optional[StrictStr] = Field(description="Email exchange server domain name (MX record value).")
    preference: Optional[StrictInt] = Field(description="MX record preference.")
    is_in_white_list: StrictBool = Field(description="`true` if the email address exists in the Textmagic whitelist. ", alias="isInWhiteList")
    is_in_black_list: StrictBool = Field(description="`true` if the email address exists in the Textmagic blacklist. ", alias="isInBlackList")
    has_mx: StrictBool = Field(description="`true` if the email address domain has an MX record. ", alias="hasMx")
    has_aa: StrictBool = Field(description="`true` if the email address domain has an A record (IPv4). ", alias="hasAa")
    has_aaaa: StrictBool = Field(description="`true` if the email address domain has an AAAA record (IPv6). ", alias="hasAaaa")
    __properties: ClassVar[List[str]] = ["address", "status", "deliverability", "reason", "risk", "addressType", "isDisposableAddress", "suggestion", "emailRole", "localPart", "domainPart", "exchange", "preference", "isInWhiteList", "isInBlackList", "hasMx", "hasAa", "hasAaaa"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['valid', 'invalid']):
            raise ValueError("must be one of enum values ('valid', 'invalid')")
        return value

    @field_validator('risk')
    def risk_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['high', 'medium', 'low', 'unknown']):
            raise ValueError("must be one of enum values ('high', 'medium', 'low', 'unknown')")
        return value

    @field_validator('address_type')
    def address_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['corporate', 'free']):
            raise ValueError("must be one of enum values ('corporate', 'free')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DoEmailLookupResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if suggestion (nullable) is None
        # and model_fields_set contains the field
        if self.suggestion is None and "suggestion" in self.model_fields_set:
            _dict['suggestion'] = None

        # set to None if email_role (nullable) is None
        # and model_fields_set contains the field
        if self.email_role is None and "email_role" in self.model_fields_set:
            _dict['emailRole'] = None

        # set to None if exchange (nullable) is None
        # and model_fields_set contains the field
        if self.exchange is None and "exchange" in self.model_fields_set:
            _dict['exchange'] = None

        # set to None if preference (nullable) is None
        # and model_fields_set contains the field
        if self.preference is None and "preference" in self.model_fields_set:
            _dict['preference'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DoEmailLookupResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "status": obj.get("status"),
            "deliverability": obj.get("deliverability"),
            "reason": obj.get("reason"),
            "risk": obj.get("risk"),
            "addressType": obj.get("addressType"),
            "isDisposableAddress": obj.get("isDisposableAddress"),
            "suggestion": obj.get("suggestion"),
            "emailRole": obj.get("emailRole"),
            "localPart": obj.get("localPart"),
            "domainPart": obj.get("domainPart"),
            "exchange": obj.get("exchange"),
            "preference": obj.get("preference"),
            "isInWhiteList": obj.get("isInWhiteList"),
            "isInBlackList": obj.get("isInBlackList"),
            "hasMx": obj.get("hasMx"),
            "hasAa": obj.get("hasAa"),
            "hasAaaa": obj.get("hasAaaa")
        })
        return _obj


