# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmailSenderItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'domain_id': 'int',
        'email': 'str',
        'created_at': 'datetime',
        'domain_status': 'str',
        'from_name': 'str',
        'reply_to': 'str'
    }

    attribute_map = {
        'id': 'id',
        'domain_id': 'domainId',
        'email': 'email',
        'created_at': 'createdAt',
        'domain_status': 'domainStatus',
        'from_name': 'fromName',
        'reply_to': 'replyTo'
    }

    def __init__(self, id=None, domain_id=None, email=None, created_at=None, domain_status=None, from_name=None, reply_to=None):  # noqa: E501
        """EmailSenderItem - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._domain_id = None
        self._email = None
        self._created_at = None
        self._domain_status = None
        self._from_name = None
        self._reply_to = None
        self.discriminator = None

        self.id = id
        self.domain_id = domain_id
        self.email = email
        self.created_at = created_at
        self.domain_status = domain_status
        if from_name is not None:
            self.from_name = from_name
        if reply_to is not None:
            self.reply_to = reply_to

    @property
    def id(self):
        """Gets the id of this EmailSenderItem.  # noqa: E501

        Unique email sender identifier.  # noqa: E501

        :return: The id of this EmailSenderItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmailSenderItem.

        Unique email sender identifier.  # noqa: E501

        :param id: The id of this EmailSenderItem.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def domain_id(self):
        """Gets the domain_id of this EmailSenderItem.  # noqa: E501

        ID of the associated domain.  # noqa: E501

        :return: The domain_id of this EmailSenderItem.  # noqa: E501
        :rtype: int
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id):
        """Sets the domain_id of this EmailSenderItem.

        ID of the associated domain.  # noqa: E501

        :param domain_id: The domain_id of this EmailSenderItem.  # noqa: E501
        :type: int
        """

        self._domain_id = domain_id

    @property
    def email(self):
        """Gets the email of this EmailSenderItem.  # noqa: E501

        Email address of the sender.  # noqa: E501

        :return: The email of this EmailSenderItem.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this EmailSenderItem.

        Email address of the sender.  # noqa: E501

        :param email: The email of this EmailSenderItem.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def created_at(self):
        """Gets the created_at of this EmailSenderItem.  # noqa: E501

        When the email sender was created.  # noqa: E501

        :return: The created_at of this EmailSenderItem.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this EmailSenderItem.

        When the email sender was created.  # noqa: E501

        :param created_at: The created_at of this EmailSenderItem.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def domain_status(self):
        """Gets the domain_status of this EmailSenderItem.  # noqa: E501

        Current verification status of the associated domain.  # noqa: E501

        :return: The domain_status of this EmailSenderItem.  # noqa: E501
        :rtype: str
        """
        return self._domain_status

    @domain_status.setter
    def domain_status(self, domain_status):
        """Sets the domain_status of this EmailSenderItem.

        Current verification status of the associated domain.  # noqa: E501

        :param domain_status: The domain_status of this EmailSenderItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["not_verified", "pending", "manual_review", "rejected", "verified"]  # noqa: E501
        if domain_status not in allowed_values:
            raise ValueError(
                "Invalid value for `domain_status` ({0}), must be one of {1}"  # noqa: E501
                .format(domain_status, allowed_values)
            )

        self._domain_status = domain_status

    @property
    def from_name(self):
        """Gets the from_name of this EmailSenderItem.  # noqa: E501

        Display name for the sender.  # noqa: E501

        :return: The from_name of this EmailSenderItem.  # noqa: E501
        :rtype: str
        """
        return self._from_name

    @from_name.setter
    def from_name(self, from_name):
        """Sets the from_name of this EmailSenderItem.

        Display name for the sender.  # noqa: E501

        :param from_name: The from_name of this EmailSenderItem.  # noqa: E501
        :type: str
        """

        self._from_name = from_name

    @property
    def reply_to(self):
        """Gets the reply_to of this EmailSenderItem.  # noqa: E501

        Reply-to email address.  # noqa: E501

        :return: The reply_to of this EmailSenderItem.  # noqa: E501
        :rtype: str
        """
        return self._reply_to

    @reply_to.setter
    def reply_to(self, reply_to):
        """Sets the reply_to of this EmailSenderItem.

        Reply-to email address.  # noqa: E501

        :param reply_to: The reply_to of this EmailSenderItem.  # noqa: E501
        :type: str
        """

        self._reply_to = reply_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailSenderItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailSenderItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
