# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EmailSenderItem(BaseModel):
    """
    EmailSenderItem
    """ # noqa: E501
    id: StrictInt = Field(description="Unique email sender identifier.")
    domain_id: StrictInt = Field(description="ID of the associated domain.", alias="domainId")
    email: StrictStr = Field(description="Email address of the sender.")
    created_at: datetime = Field(description="When the email sender was created.", alias="createdAt")
    domain_status: StrictStr = Field(description="Current verification status of the associated domain.", alias="domainStatus")
    from_name: Optional[StrictStr] = Field(default=None, description="Display name for the sender.", alias="fromName")
    reply_to: Optional[StrictStr] = Field(default=None, description="Reply-to email address.", alias="replyTo")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "domainId", "email", "createdAt", "domainStatus", "fromName", "replyTo"]

    @field_validator('domain_status')
    def domain_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['not_verified', 'pending', 'manual_review', 'rejected', 'verified']):
            raise ValueError("must be one of enum values ('not_verified', 'pending', 'manual_review', 'rejected', 'verified')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailSenderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if from_name (nullable) is None
        # and model_fields_set contains the field
        if self.from_name is None and "from_name" in self.model_fields_set:
            _dict['fromName'] = None

        # set to None if reply_to (nullable) is None
        # and model_fields_set contains the field
        if self.reply_to is None and "reply_to" in self.model_fields_set:
            _dict['replyTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailSenderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "domainId": obj.get("domainId"),
            "email": obj.get("email"),
            "createdAt": obj.get("createdAt"),
            "domainStatus": obj.get("domainStatus"),
            "fromName": obj.get("fromName"),
            "replyTo": obj.get("replyTo")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


