# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetOutboundMessagesHistoryPaginatedResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_id': 'int',
        'next_last_id': 'int',
        'limit': 'int',
        'resources': 'list[MessageOut]'
    }

    attribute_map = {
        'last_id': 'lastId',
        'next_last_id': 'nextLastId',
        'limit': 'limit',
        'resources': 'resources'
    }

    def __init__(self, last_id=None, next_last_id=None, limit=None, resources=None):  # noqa: E501
        """GetOutboundMessagesHistoryPaginatedResponse - a model defined in Swagger"""  # noqa: E501

        self._last_id = None
        self._next_last_id = None
        self._limit = None
        self._resources = None
        self.discriminator = None

        self.last_id = last_id
        self.next_last_id = next_last_id
        self.limit = limit
        self.resources = resources

    @property
    def last_id(self):
        """Gets the last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501


        :return: The last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :rtype: int
        """
        return self._last_id

    @last_id.setter
    def last_id(self, last_id):
        """Sets the last_id of this GetOutboundMessagesHistoryPaginatedResponse.


        :param last_id: The last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :type: int
        """

        self._last_id = last_id

    @property
    def next_last_id(self):
        """Gets the next_last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501


        :return: The next_last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :rtype: int
        """
        return self._next_last_id

    @next_last_id.setter
    def next_last_id(self, next_last_id):
        """Sets the next_last_id of this GetOutboundMessagesHistoryPaginatedResponse.


        :param next_last_id: The next_last_id of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :type: int
        """

        self._next_last_id = next_last_id

    @property
    def limit(self):
        """Gets the limit of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501

        The number of results per page.  # noqa: E501

        :return: The limit of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetOutboundMessagesHistoryPaginatedResponse.

        The number of results per page.  # noqa: E501

        :param limit: The limit of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def resources(self):
        """Gets the resources of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501


        :return: The resources of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :rtype: list[MessageOut]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this GetOutboundMessagesHistoryPaginatedResponse.


        :param resources: The resources of this GetOutboundMessagesHistoryPaginatedResponse.  # noqa: E501
        :type: list[MessageOut]
        """

        self._resources = resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOutboundMessagesHistoryPaginatedResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOutboundMessagesHistoryPaginatedResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
