# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict
from typing import Optional, Set
from typing_extensions import Self

class GetBalanceNotificationOptionsResponse(BaseModel):
    """
    GetBalanceNotificationOptionsResponse
    """ # noqa: E501
    var_1: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="1")
    var_2: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="2")
    var_3: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="3")
    var_5: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="5")
    var_10: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="10")
    var_20: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="20")
    var_30: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="30")
    var_50: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="50")
    var_100: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="100")
    var_500: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="500")
    var_1000: StrictStr = Field(description="Contains sign of currency in Unicode hex code.", alias="1000")
    __properties: ClassVar[List[str]] = ["1", "2", "3", "5", "10", "20", "30", "50", "100", "500", "1000"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBalanceNotificationOptionsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBalanceNotificationOptionsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "1": obj.get("1"),
            "2": obj.get("2"),
            "3": obj.get("3"),
            "5": obj.get("5"),
            "10": obj.get("10"),
            "20": obj.get("20"),
            "30": obj.get("30"),
            "50": obj.get("50"),
            "100": obj.get("100"),
            "500": obj.get("500"),
            "1000": obj.get("1000")
        })
        return _obj


