# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional, Union
from TextMagic.models.message_out_sender_source import MessageOutSenderSource
from TextMagic.models.message_out_session import MessageOutSession
from typing import Optional, Set
from typing_extensions import Self

class MessageOut(BaseModel):
    """
    MessageOut
    """ # noqa: E501
    id: StrictInt = Field(description="Message ID.")
    sender: Optional[StrictStr] = Field(default=None, description="Message sender (phone number or alphanumeric Sender ID).")
    receiver: Optional[StrictStr] = Field(default=None, description="Recipient`s phone number.")
    text: StrictStr
    status: StrictStr = Field(description="Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. ")
    reject_reason: Optional[StrictStr] = Field(default=None, description="Rejection reason.", alias="rejectReason")
    contact_id: Optional[StrictInt] = Field(description="Recipient contact ID.", alias="contactId")
    session_id: Optional[StrictInt] = Field(description="Message Session ID of a message.", alias="sessionId")
    message_time: datetime = Field(description="Sending time.", alias="messageTime")
    avatar: Optional[StrictStr]
    deleted: Optional[StrictBool] = Field(default=None, description="Indicates that the message has been deleted.")
    delivered_at: Optional[datetime] = Field(default=None, description="Time when message was delivered.", alias="deliveredAt")
    charset: Optional[StrictStr] = Field(description="Message charset. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS. ")
    charset_label: Optional[StrictStr] = Field(description="Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. ", alias="charsetLabel")
    first_name: Optional[StrictStr] = Field(description="Contact first name. Could be substituted from your [Contacts](https://docs.textmagic.com/#tag/Contacts) (even if you submitted the phone number instead of the contact ID). ", alias="firstName")
    last_name: Optional[StrictStr] = Field(description="Contact last name.", alias="lastName")
    country: Optional[StrictStr] = Field(description="The 2-letter ISO country code of the recipient's phone number. ")
    phone: Optional[StrictStr] = Field(default=None, description="Receipent`s phone number.")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Message price.")
    parts_count: Optional[StrictInt] = Field(description="Message parts (multiples of 160 characters) count.", alias="partsCount")
    from_email: Optional[StrictStr] = Field(default=None, description="The user email which this message came from. For Email2SMS and Distribution Lists the messages, it is an original email address - in other cases, it is an account email address.", alias="fromEmail")
    from_number: Optional[StrictStr] = Field(default=None, description="The Phone number used to send the SMS.", alias="fromNumber")
    sender_source: Optional[MessageOutSenderSource] = Field(default=None, alias="senderSource")
    session: Optional[MessageOutSession] = None
    __properties: ClassVar[List[str]] = ["id", "sender", "receiver", "text", "status", "rejectReason", "contactId", "sessionId", "messageTime", "avatar", "deleted", "deliveredAt", "charset", "charsetLabel", "firstName", "lastName", "country", "phone", "price", "partsCount", "fromEmail", "fromNumber", "senderSource", "session"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['q', 's', 'e', 'r', 'a', 'd', 'b', 'f', 'u', 'j', 'i', 'p', 'h']):
            raise ValueError("must be one of enum values ('q', 's', 'e', 'r', 'a', 'd', 'b', 'f', 'u', 'j', 'i', 'p', 'h')")
        return value

    @field_validator('reject_reason')
    def reject_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['a', 'f', 'l', 'c', 'u', 'b', 's', 'm', 'n', 'i', 'if', 'd', 't', 'e', 'h', 'k', 'r', 'g', 'j', 'w', 'v', 'q', 'x', 'o', 'p']):
            raise ValueError("must be one of enum values ('a', 'f', 'l', 'c', 'u', 'b', 's', 'm', 'n', 'i', 'if', 'd', 't', 'e', 'h', 'k', 'r', 'g', 'j', 'w', 'v', 'q', 'x', 'o', 'p')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sender_source
        if self.sender_source:
            _dict['senderSource'] = self.sender_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # set to None if sender (nullable) is None
        # and model_fields_set contains the field
        if self.sender is None and "sender" in self.model_fields_set:
            _dict['sender'] = None

        # set to None if contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_id is None and "contact_id" in self.model_fields_set:
            _dict['contactId'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['sessionId'] = None

        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict['avatar'] = None

        # set to None if delivered_at (nullable) is None
        # and model_fields_set contains the field
        if self.delivered_at is None and "delivered_at" in self.model_fields_set:
            _dict['deliveredAt'] = None

        # set to None if charset (nullable) is None
        # and model_fields_set contains the field
        if self.charset is None and "charset" in self.model_fields_set:
            _dict['charset'] = None

        # set to None if charset_label (nullable) is None
        # and model_fields_set contains the field
        if self.charset_label is None and "charset_label" in self.model_fields_set:
            _dict['charsetLabel'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['lastName'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if parts_count (nullable) is None
        # and model_fields_set contains the field
        if self.parts_count is None and "parts_count" in self.model_fields_set:
            _dict['partsCount'] = None

        # set to None if from_email (nullable) is None
        # and model_fields_set contains the field
        if self.from_email is None and "from_email" in self.model_fields_set:
            _dict['fromEmail'] = None

        # set to None if from_number (nullable) is None
        # and model_fields_set contains the field
        if self.from_number is None and "from_number" in self.model_fields_set:
            _dict['fromNumber'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sender": obj.get("sender"),
            "receiver": obj.get("receiver"),
            "text": obj.get("text"),
            "status": obj.get("status"),
            "rejectReason": obj.get("rejectReason"),
            "contactId": obj.get("contactId"),
            "sessionId": obj.get("sessionId"),
            "messageTime": obj.get("messageTime"),
            "avatar": obj.get("avatar"),
            "deleted": obj.get("deleted"),
            "deliveredAt": obj.get("deliveredAt"),
            "charset": obj.get("charset"),
            "charsetLabel": obj.get("charsetLabel"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "country": obj.get("country"),
            "phone": obj.get("phone"),
            "price": obj.get("price"),
            "partsCount": obj.get("partsCount"),
            "fromEmail": obj.get("fromEmail"),
            "fromNumber": obj.get("fromNumber"),
            "senderSource": MessageOutSenderSource.from_dict(obj["senderSource"]) if obj.get("senderSource") is not None else None,
            "session": MessageOutSession.from_dict(obj["session"]) if obj.get("session") is not None else None
        })
        return _obj


