# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MessagesIcsParametersRecipients(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contacts': 'list[int]',
        'groups': 'list[int]',
        'numbers': 'list[str]'
    }

    attribute_map = {
        'contacts': 'contacts',
        'groups': 'groups',
        'numbers': 'numbers'
    }

    def __init__(self, contacts=None, groups=None, numbers=None):  # noqa: E501
        """MessagesIcsParametersRecipients - a model defined in Swagger"""  # noqa: E501

        self._contacts = None
        self._groups = None
        self._numbers = None
        self.discriminator = None

        self.contacts = contacts
        self.groups = groups
        self.numbers = numbers

    @property
    def contacts(self):
        """Gets the contacts of this MessagesIcsParametersRecipients.  # noqa: E501


        :return: The contacts of this MessagesIcsParametersRecipients.  # noqa: E501
        :rtype: list[int]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this MessagesIcsParametersRecipients.


        :param contacts: The contacts of this MessagesIcsParametersRecipients.  # noqa: E501
        :type: list[int]
        """

        self._contacts = contacts

    @property
    def groups(self):
        """Gets the groups of this MessagesIcsParametersRecipients.  # noqa: E501


        :return: The groups of this MessagesIcsParametersRecipients.  # noqa: E501
        :rtype: list[int]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this MessagesIcsParametersRecipients.


        :param groups: The groups of this MessagesIcsParametersRecipients.  # noqa: E501
        :type: list[int]
        """

        self._groups = groups

    @property
    def numbers(self):
        """Gets the numbers of this MessagesIcsParametersRecipients.  # noqa: E501


        :return: The numbers of this MessagesIcsParametersRecipients.  # noqa: E501
        :rtype: list[str]
        """
        return self._numbers

    @numbers.setter
    def numbers(self, numbers):
        """Sets the numbers of this MessagesIcsParametersRecipients.


        :param numbers: The numbers of this MessagesIcsParametersRecipients.  # noqa: E501
        :type: list[str]
        """

        self._numbers = numbers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagesIcsParametersRecipients, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagesIcsParametersRecipients):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
