# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class OutboundEmailResponse(BaseModel):
    """
    OutboundEmailResponse
    """ # noqa: E501
    id: StrictInt = Field(description="Outbound email ID.")
    send_time: datetime = Field(description="Email send timestamp.", alias="sendTime")
    from_name: Optional[StrictStr] = Field(default=None, description="Sender name.", alias="fromName")
    from_email: StrictStr = Field(description="Sender email address.", alias="fromEmail")
    reply_to_email: StrictStr = Field(description="Reply-to email address.", alias="replyToEmail")
    recipient_full_name: Optional[StrictStr] = Field(default=None, description="Recipient's full name.", alias="recipientFullName")
    recipient_email: Optional[StrictStr] = Field(default=None, description="Recipient's email address.", alias="recipientEmail")
    email_subject: StrictStr = Field(description="Email subject line.", alias="emailSubject")
    email_content: StrictStr = Field(description="HTML email content.", alias="emailContent")
    source: StrictStr = Field(description="Source of the outbound email.")
    status: StrictStr = Field(description="Current email status.")
    cost: Union[StrictFloat, StrictInt] = Field(description="Cost of sending this email.")
    status_reason: Optional[StrictStr] = Field(default=None, description="Detailed status reason.", alias="statusReason")
    contact_id: Optional[StrictInt] = Field(default=None, description="Associated contact ID.", alias="contactId")
    initiator_id: StrictInt = Field(description="ID of user who initiated the email.", alias="initiatorId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "sendTime", "fromName", "fromEmail", "replyToEmail", "recipientFullName", "recipientEmail", "emailSubject", "emailContent", "source", "status", "cost", "statusReason", "contactId", "initiatorId"]

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['emailCampaign', 'ticket']):
            raise ValueError("must be one of enum values ('emailCampaign', 'ticket')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'sent', 'delivered', 'rejected', 'failed', 'opened', 'clicked', 'unsubscribed', 'spam']):
            raise ValueError("must be one of enum values ('pending', 'sent', 'delivered', 'rejected', 'failed', 'opened', 'clicked', 'unsubscribed', 'spam')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutboundEmailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if from_name (nullable) is None
        # and model_fields_set contains the field
        if self.from_name is None and "from_name" in self.model_fields_set:
            _dict['fromName'] = None

        # set to None if recipient_full_name (nullable) is None
        # and model_fields_set contains the field
        if self.recipient_full_name is None and "recipient_full_name" in self.model_fields_set:
            _dict['recipientFullName'] = None

        # set to None if recipient_email (nullable) is None
        # and model_fields_set contains the field
        if self.recipient_email is None and "recipient_email" in self.model_fields_set:
            _dict['recipientEmail'] = None

        # set to None if status_reason (nullable) is None
        # and model_fields_set contains the field
        if self.status_reason is None and "status_reason" in self.model_fields_set:
            _dict['statusReason'] = None

        # set to None if contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_id is None and "contact_id" in self.model_fields_set:
            _dict['contactId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutboundEmailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sendTime": obj.get("sendTime"),
            "fromName": obj.get("fromName"),
            "fromEmail": obj.get("fromEmail"),
            "replyToEmail": obj.get("replyToEmail"),
            "recipientFullName": obj.get("recipientFullName"),
            "recipientEmail": obj.get("recipientEmail"),
            "emailSubject": obj.get("emailSubject"),
            "emailContent": obj.get("emailContent"),
            "source": obj.get("source"),
            "status": obj.get("status"),
            "cost": obj.get("cost"),
            "statusReason": obj.get("statusReason"),
            "contactId": obj.get("contactId"),
            "initiatorId": obj.get("initiatorId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


