# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScheduleEmailCampaignInputObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email_sender_id': 'int',
        'subject': 'str',
        'message': 'str',
        'from_name': 'str',
        'reply_to_email': 'str',
        'recipients': 'Apiv2emailcampaignsscheduleRecipients',
        'schedule_params': 'Apiv2emailcampaignsscheduleScheduleParams'
    }

    attribute_map = {
        'email_sender_id': 'emailSenderId',
        'subject': 'subject',
        'message': 'message',
        'from_name': 'fromName',
        'reply_to_email': 'replyToEmail',
        'recipients': 'recipients',
        'schedule_params': 'scheduleParams'
    }

    def __init__(self, email_sender_id=None, subject=None, message=None, from_name=None, reply_to_email=None, recipients=None, schedule_params=None):  # noqa: E501
        """ScheduleEmailCampaignInputObject - a model defined in Swagger"""  # noqa: E501

        self._email_sender_id = None
        self._subject = None
        self._message = None
        self._from_name = None
        self._reply_to_email = None
        self._recipients = None
        self._schedule_params = None
        self.discriminator = None

        if email_sender_id is not None:
            self.email_sender_id = email_sender_id
        if subject is not None:
            self.subject = subject
        if message is not None:
            self.message = message
        if from_name is not None:
            self.from_name = from_name
        if reply_to_email is not None:
            self.reply_to_email = reply_to_email
        if recipients is not None:
            self.recipients = recipients
        if schedule_params is not None:
            self.schedule_params = schedule_params

    @property
    def email_sender_id(self):
        """Gets the email_sender_id of this ScheduleEmailCampaignInputObject.  # noqa: E501

        Email sender ID from your configured senders.  # noqa: E501

        :return: The email_sender_id of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: int
        """
        return self._email_sender_id

    @email_sender_id.setter
    def email_sender_id(self, email_sender_id):
        """Sets the email_sender_id of this ScheduleEmailCampaignInputObject.

        Email sender ID from your configured senders.  # noqa: E501

        :param email_sender_id: The email_sender_id of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: int
        """

        self._email_sender_id = email_sender_id

    @property
    def subject(self):
        """Gets the subject of this ScheduleEmailCampaignInputObject.  # noqa: E501

        Email subject line.  # noqa: E501

        :return: The subject of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this ScheduleEmailCampaignInputObject.

        Email subject line.  # noqa: E501

        :param subject: The subject of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: str
        """
        if subject is not None and len(subject) > 998:
            raise ValueError("Invalid value for `subject`, length must be less than or equal to `998`")  # noqa: E501

        self._subject = subject

    @property
    def message(self):
        """Gets the message of this ScheduleEmailCampaignInputObject.  # noqa: E501

        HTML email content.  # noqa: E501

        :return: The message of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ScheduleEmailCampaignInputObject.

        HTML email content.  # noqa: E501

        :param message: The message of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def from_name(self):
        """Gets the from_name of this ScheduleEmailCampaignInputObject.  # noqa: E501

        Optional custom sender name.  # noqa: E501

        :return: The from_name of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: str
        """
        return self._from_name

    @from_name.setter
    def from_name(self, from_name):
        """Sets the from_name of this ScheduleEmailCampaignInputObject.

        Optional custom sender name.  # noqa: E501

        :param from_name: The from_name of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: str
        """
        if from_name is not None and len(from_name) > 500:
            raise ValueError("Invalid value for `from_name`, length must be less than or equal to `500`")  # noqa: E501

        self._from_name = from_name

    @property
    def reply_to_email(self):
        """Gets the reply_to_email of this ScheduleEmailCampaignInputObject.  # noqa: E501

        Optional custom reply-to email address.  # noqa: E501

        :return: The reply_to_email of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: str
        """
        return self._reply_to_email

    @reply_to_email.setter
    def reply_to_email(self, reply_to_email):
        """Sets the reply_to_email of this ScheduleEmailCampaignInputObject.

        Optional custom reply-to email address.  # noqa: E501

        :param reply_to_email: The reply_to_email of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: str
        """

        self._reply_to_email = reply_to_email

    @property
    def recipients(self):
        """Gets the recipients of this ScheduleEmailCampaignInputObject.  # noqa: E501


        :return: The recipients of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: Apiv2emailcampaignsscheduleRecipients
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """Sets the recipients of this ScheduleEmailCampaignInputObject.


        :param recipients: The recipients of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: Apiv2emailcampaignsscheduleRecipients
        """

        self._recipients = recipients

    @property
    def schedule_params(self):
        """Gets the schedule_params of this ScheduleEmailCampaignInputObject.  # noqa: E501


        :return: The schedule_params of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :rtype: Apiv2emailcampaignsscheduleScheduleParams
        """
        return self._schedule_params

    @schedule_params.setter
    def schedule_params(self, schedule_params):
        """Sets the schedule_params of this ScheduleEmailCampaignInputObject.


        :param schedule_params: The schedule_params of this ScheduleEmailCampaignInputObject.  # noqa: E501
        :type: Apiv2emailcampaignsscheduleScheduleParams
        """

        self._schedule_params = schedule_params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduleEmailCampaignInputObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduleEmailCampaignInputObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
