# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScheduledEmailCampaignDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'status': 'str',
        'email_sender_id': 'int',
        'start_at': 'datetime',
        'end_at': 'datetime',
        'next_send_at': 'datetime',
        'created_by': 'UserPersonalInfo',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'type': 'str',
        'from_name': 'str',
        'from_email': 'str',
        'reply_to_email': 'str',
        'subject': 'str',
        'html': 'str',
        'recipients_count': 'int',
        'sending_timezone': 'str',
        'rrule': 'str',
        'occurrence_summary': 'str'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'email_sender_id': 'emailSenderId',
        'start_at': 'startAt',
        'end_at': 'endAt',
        'next_send_at': 'nextSendAt',
        'created_by': 'createdBy',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'type': 'type',
        'from_name': 'fromName',
        'from_email': 'fromEmail',
        'reply_to_email': 'replyToEmail',
        'subject': 'subject',
        'html': 'html',
        'recipients_count': 'recipientsCount',
        'sending_timezone': 'sendingTimezone',
        'rrule': 'rrule',
        'occurrence_summary': 'occurrenceSummary'
    }

    def __init__(self, id=None, status=None, email_sender_id=None, start_at=None, end_at=None, next_send_at=None, created_by=None, created_at=None, updated_at=None, type=None, from_name=None, from_email=None, reply_to_email=None, subject=None, html=None, recipients_count=None, sending_timezone=None, rrule=None, occurrence_summary=None):  # noqa: E501
        """ScheduledEmailCampaignDetails - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._status = None
        self._email_sender_id = None
        self._start_at = None
        self._end_at = None
        self._next_send_at = None
        self._created_by = None
        self._created_at = None
        self._updated_at = None
        self._type = None
        self._from_name = None
        self._from_email = None
        self._reply_to_email = None
        self._subject = None
        self._html = None
        self._recipients_count = None
        self._sending_timezone = None
        self._rrule = None
        self._occurrence_summary = None
        self.discriminator = None

        self.id = id
        self.status = status
        if email_sender_id is not None:
            self.email_sender_id = email_sender_id
        self.start_at = start_at
        if end_at is not None:
            self.end_at = end_at
        if next_send_at is not None:
            self.next_send_at = next_send_at
        self.created_by = created_by
        self.created_at = created_at
        self.updated_at = updated_at
        self.type = type
        if from_name is not None:
            self.from_name = from_name
        self.from_email = from_email
        self.reply_to_email = reply_to_email
        self.subject = subject
        self.html = html
        self.recipients_count = recipients_count
        self.sending_timezone = sending_timezone
        if rrule is not None:
            self.rrule = rrule
        if occurrence_summary is not None:
            self.occurrence_summary = occurrence_summary

    @property
    def id(self):
        """Gets the id of this ScheduledEmailCampaignDetails.  # noqa: E501

        Unique scheduled campaign ID.  # noqa: E501

        :return: The id of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ScheduledEmailCampaignDetails.

        Unique scheduled campaign ID.  # noqa: E501

        :param id: The id of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this ScheduledEmailCampaignDetails.  # noqa: E501

        Current scheduled campaign status.  # noqa: E501

        :return: The status of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ScheduledEmailCampaignDetails.

        Current scheduled campaign status.  # noqa: E501

        :param status: The status of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["scheduled", "active", "paused", "completed", "cancelled", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def email_sender_id(self):
        """Gets the email_sender_id of this ScheduledEmailCampaignDetails.  # noqa: E501

        Email sender ID used for this campaign.  # noqa: E501

        :return: The email_sender_id of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: int
        """
        return self._email_sender_id

    @email_sender_id.setter
    def email_sender_id(self, email_sender_id):
        """Sets the email_sender_id of this ScheduledEmailCampaignDetails.

        Email sender ID used for this campaign.  # noqa: E501

        :param email_sender_id: The email_sender_id of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: int
        """

        self._email_sender_id = email_sender_id

    @property
    def start_at(self):
        """Gets the start_at of this ScheduledEmailCampaignDetails.  # noqa: E501

        Scheduled start timestamp (UTC).  # noqa: E501

        :return: The start_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this ScheduledEmailCampaignDetails.

        Scheduled start timestamp (UTC).  # noqa: E501

        :param start_at: The start_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: datetime
        """

        self._start_at = start_at

    @property
    def end_at(self):
        """Gets the end_at of this ScheduledEmailCampaignDetails.  # noqa: E501

        End timestamp for recurring campaigns (UTC).  # noqa: E501

        :return: The end_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._end_at

    @end_at.setter
    def end_at(self, end_at):
        """Sets the end_at of this ScheduledEmailCampaignDetails.

        End timestamp for recurring campaigns (UTC).  # noqa: E501

        :param end_at: The end_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: datetime
        """

        self._end_at = end_at

    @property
    def next_send_at(self):
        """Gets the next_send_at of this ScheduledEmailCampaignDetails.  # noqa: E501

        Next scheduled send timestamp (UTC).  # noqa: E501

        :return: The next_send_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._next_send_at

    @next_send_at.setter
    def next_send_at(self, next_send_at):
        """Sets the next_send_at of this ScheduledEmailCampaignDetails.

        Next scheduled send timestamp (UTC).  # noqa: E501

        :param next_send_at: The next_send_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: datetime
        """

        self._next_send_at = next_send_at

    @property
    def created_by(self):
        """Gets the created_by of this ScheduledEmailCampaignDetails.  # noqa: E501


        :return: The created_by of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: UserPersonalInfo
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ScheduledEmailCampaignDetails.


        :param created_by: The created_by of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: UserPersonalInfo
        """

        self._created_by = created_by

    @property
    def created_at(self):
        """Gets the created_at of this ScheduledEmailCampaignDetails.  # noqa: E501

        Campaign creation timestamp.  # noqa: E501

        :return: The created_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ScheduledEmailCampaignDetails.

        Campaign creation timestamp.  # noqa: E501

        :param created_at: The created_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ScheduledEmailCampaignDetails.  # noqa: E501

        Last update timestamp.  # noqa: E501

        :return: The updated_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ScheduledEmailCampaignDetails.

        Last update timestamp.  # noqa: E501

        :param updated_at: The updated_at of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def type(self):
        """Gets the type of this ScheduledEmailCampaignDetails.  # noqa: E501

        Campaign recurrence type.  # noqa: E501

        :return: The type of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ScheduledEmailCampaignDetails.

        Campaign recurrence type.  # noqa: E501

        :param type: The type of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["once", "hourly", "daily", "weekly", "monthly", "yearly", "follow-up"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def from_name(self):
        """Gets the from_name of this ScheduledEmailCampaignDetails.  # noqa: E501

        Sender name displayed in recipient's inbox.  # noqa: E501

        :return: The from_name of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._from_name

    @from_name.setter
    def from_name(self, from_name):
        """Sets the from_name of this ScheduledEmailCampaignDetails.

        Sender name displayed in recipient's inbox.  # noqa: E501

        :param from_name: The from_name of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._from_name = from_name

    @property
    def from_email(self):
        """Gets the from_email of this ScheduledEmailCampaignDetails.  # noqa: E501

        Sender email address.  # noqa: E501

        :return: The from_email of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._from_email

    @from_email.setter
    def from_email(self, from_email):
        """Sets the from_email of this ScheduledEmailCampaignDetails.

        Sender email address.  # noqa: E501

        :param from_email: The from_email of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._from_email = from_email

    @property
    def reply_to_email(self):
        """Gets the reply_to_email of this ScheduledEmailCampaignDetails.  # noqa: E501

        Reply-to email address.  # noqa: E501

        :return: The reply_to_email of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._reply_to_email

    @reply_to_email.setter
    def reply_to_email(self, reply_to_email):
        """Sets the reply_to_email of this ScheduledEmailCampaignDetails.

        Reply-to email address.  # noqa: E501

        :param reply_to_email: The reply_to_email of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._reply_to_email = reply_to_email

    @property
    def subject(self):
        """Gets the subject of this ScheduledEmailCampaignDetails.  # noqa: E501

        Email subject line.  # noqa: E501

        :return: The subject of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this ScheduledEmailCampaignDetails.

        Email subject line.  # noqa: E501

        :param subject: The subject of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._subject = subject

    @property
    def html(self):
        """Gets the html of this ScheduledEmailCampaignDetails.  # noqa: E501

        HTML email content.  # noqa: E501

        :return: The html of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._html

    @html.setter
    def html(self, html):
        """Sets the html of this ScheduledEmailCampaignDetails.

        HTML email content.  # noqa: E501

        :param html: The html of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._html = html

    @property
    def recipients_count(self):
        """Gets the recipients_count of this ScheduledEmailCampaignDetails.  # noqa: E501

        Number of recipients for this campaign.  # noqa: E501

        :return: The recipients_count of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: int
        """
        return self._recipients_count

    @recipients_count.setter
    def recipients_count(self, recipients_count):
        """Sets the recipients_count of this ScheduledEmailCampaignDetails.

        Number of recipients for this campaign.  # noqa: E501

        :param recipients_count: The recipients_count of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: int
        """

        self._recipients_count = recipients_count

    @property
    def sending_timezone(self):
        """Gets the sending_timezone of this ScheduledEmailCampaignDetails.  # noqa: E501

        Timezone for sending the campaign.  # noqa: E501

        :return: The sending_timezone of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._sending_timezone

    @sending_timezone.setter
    def sending_timezone(self, sending_timezone):
        """Sets the sending_timezone of this ScheduledEmailCampaignDetails.

        Timezone for sending the campaign.  # noqa: E501

        :param sending_timezone: The sending_timezone of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._sending_timezone = sending_timezone

    @property
    def rrule(self):
        """Gets the rrule of this ScheduledEmailCampaignDetails.  # noqa: E501

        RFC 5545 recurrence rule for recurring campaigns.  # noqa: E501

        :return: The rrule of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._rrule

    @rrule.setter
    def rrule(self, rrule):
        """Sets the rrule of this ScheduledEmailCampaignDetails.

        RFC 5545 recurrence rule for recurring campaigns.  # noqa: E501

        :param rrule: The rrule of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._rrule = rrule

    @property
    def occurrence_summary(self):
        """Gets the occurrence_summary of this ScheduledEmailCampaignDetails.  # noqa: E501

        Human-readable schedule description.  # noqa: E501

        :return: The occurrence_summary of this ScheduledEmailCampaignDetails.  # noqa: E501
        :rtype: str
        """
        return self._occurrence_summary

    @occurrence_summary.setter
    def occurrence_summary(self, occurrence_summary):
        """Sets the occurrence_summary of this ScheduledEmailCampaignDetails.

        Human-readable schedule description.  # noqa: E501

        :param occurrence_summary: The occurrence_summary of this ScheduledEmailCampaignDetails.  # noqa: E501
        :type: str
        """

        self._occurrence_summary = occurrence_summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduledEmailCampaignDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduledEmailCampaignDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
