# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SendMessageRequest(BaseModel):
    """
    SendMessageRequest
    """ # noqa: E501
    text: Optional[StrictStr] = Field(default=None, description="Message text. Required if the **template_id** is not set.")
    template_id: Optional[StrictInt] = Field(default=None, description="Template used instead of message text. Required if the **text** is not set.", alias="templateId")
    sending_time: Optional[StrictInt] = Field(default=None, description="DEPRECATED, consider using sendingDateTime and sendingTimezone parameters instead: Optional (required with rrule set). Message sending time in unix timestamp format. Default is now.", alias="sendingTime")
    sending_date_time: Optional[StrictStr] = Field(default=None, description="Sending time in Y-m-d H:i:s format (e.g. 2022-05-27 13:05:10). This time is relative to **sendingTimezone**. Note: for correct operation, the value of seconds must not be less than 10.", alias="sendingDateTime")
    sending_timezone: Optional[StrictStr] = Field(default=None, description="ID or ISO-name of timezone used for sending when sendingDateTime parameter is set. E.g. if you specify sendingDateTime = \\\"2016-05-27 13:02:33\\\" and sendingTimezone = \\\"America/Buenos_Aires\\\", your message will be sent at May 27, 2016 13:02:33 Buenos Aires time, or 16:02:33 UTC. Default is account timezone.", alias="sendingTimezone")
    contacts: Optional[StrictStr] = Field(default=None, description="Comma separated array of contact resources id message will be sent to.")
    lists: Optional[StrictStr] = Field(default=None, description="Comma separated array of list resources id message will be sent to.")
    phones: Optional[StrictStr] = Field(default=None, description="Comma separated array of E.164 phone numbers message will be sent to.")
    cut_extra: Optional[StrictBool] = Field(default=False, description="Should sending method cut extra characters which not fit supplied partsCount or return 400 Bad request response instead.", alias="cutExtra")
    parts_count: Optional[StrictInt] = Field(default=None, description="Maximum message parts count (Textmagic allows sending 1 to 6 message parts).", alias="partsCount")
    reference_id: Optional[StrictInt] = Field(default=None, description="Custom message reference id which can be used in your application infrastructure.", alias="referenceId")
    var_from: Optional[StrictStr] = Field(default=None, description="One of allowed Sender ID (phone number or alphanumeric sender ID). If specified Sender ID is not allowed for some destinations, a fallback default Sender ID will be used to ensure delivery. See [Get timezones](https://docs.textmagic.com/#tag/Sender-IDs).", alias="from")
    rrule: Optional[StrictStr] = Field(default=None, description="iCal RRULE parameter to create recurrent scheduled messages. When used, sendingTime is mandatory as start point of sending. See https://www.textmagic.com/free-tools/rrule-generator for format details.")
    create_chat: Optional[StrictBool] = Field(default=False, description="Should sending method try to create new Chat (if not exist) with specified recipients?", alias="createChat")
    tts: Optional[StrictBool] = Field(default=False, description="Send a Text-to-Speech message.")
    local: Optional[StrictBool] = Field(default=False, description="Treat phone numbers passed in the \\'phones\\' field as local.")
    local_country: Optional[StrictStr] = Field(default=None, description="The 2-letter ISO country code for local phone numbers, used when \\'local\\' is set to true. Default is the account country.", alias="localCountry")
    destination: Optional[StrictStr] = Field(default=None, description="Messsage destination type allowed [mms, tts].")
    resources: Optional[StrictStr] = Field(default=None, description="File name from mms attachment response (named as resource)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["text", "templateId", "sendingTime", "sendingDateTime", "sendingTimezone", "contacts", "lists", "phones", "cutExtra", "partsCount", "referenceId", "from", "rrule", "createChat", "tts", "local", "localCountry", "destination", "resources"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "templateId": obj.get("templateId"),
            "sendingTime": obj.get("sendingTime"),
            "sendingDateTime": obj.get("sendingDateTime"),
            "sendingTimezone": obj.get("sendingTimezone"),
            "contacts": obj.get("contacts"),
            "lists": obj.get("lists"),
            "phones": obj.get("phones"),
            "cutExtra": obj.get("cutExtra") if obj.get("cutExtra") is not None else False,
            "partsCount": obj.get("partsCount"),
            "referenceId": obj.get("referenceId"),
            "from": obj.get("from"),
            "rrule": obj.get("rrule"),
            "createChat": obj.get("createChat") if obj.get("createChat") is not None else False,
            "tts": obj.get("tts") if obj.get("tts") is not None else False,
            "local": obj.get("local") if obj.get("local") is not None else False,
            "localCountry": obj.get("localCountry"),
            "destination": obj.get("destination"),
            "resources": obj.get("resources")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


