# coding: utf-8

"""
    Textmagic API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateCallbackSettingsRequest(BaseModel):
    """
    UpdateCallbackSettingsRequest
    """ # noqa: E501
    out_url: Optional[StrictStr] = Field(default=None, description="This URL is used to push message delivery status updates to your application.", alias="outUrl")
    in_url: Optional[StrictStr] = Field(default=None, description="This URL is used to push incoming SMS to your application.", alias="inUrl")
    format: Optional[StrictStr] = Field(default=None, description="Desired callback data format. m - multipart/form-data, u - application/x-www-form-urlencoded, j - application/json")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["outUrl", "inUrl", "format"]

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['m', 'u', 'j']):
            raise ValueError("must be one of enum values ('m', 'u', 'j')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateCallbackSettingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if out_url (nullable) is None
        # and model_fields_set contains the field
        if self.out_url is None and "out_url" in self.model_fields_set:
            _dict['outUrl'] = None

        # set to None if in_url (nullable) is None
        # and model_fields_set contains the field
        if self.in_url is None and "in_url" in self.model_fields_set:
            _dict['inUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateCallbackSettingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "outUrl": obj.get("outUrl"),
            "inUrl": obj.get("inUrl"),
            "format": obj.get("format")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


